name: Worflow
on: push

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup network
        run: |
          docker network create --driver bridge set08103-group4
          docker pull mongo
          docker run -d --name mongo-dbserver --network set08103-group4 mongo
      - name: Build with Maven
        run: mvn package
      - name: Build
        run: docker build -t set08103-group4 .
      - name: Run image
        run: docker run --network set08103-Group4 --name semcontainer set08103-group4
      - name: view logs
        run: docker logs semcontainer
      - name: Unit Tests
        run: mvn -Dtest=com.napier.sem.appTesting test
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker-compose up --abort-on-container-exit